### ISSUE TITLE
Merge or not ? 

### ISSUE THREAD

**Issue by kisst** [apiraino/otp-cli-tool#1]
Hey @apiraino as you can see I forked and took apart your script, made quite a few changes.

I'm in debate to send a PR or not on one side I prefer to keep things streamline and having X fork is just not really the way forward in my opinion, but I made significant changes to fit it for my use-case, and not sure that you would be happy with that. 
If you are interested have a look at the changes I made and let's try to come to a common ground.

**Comment by apiraino** [comment]
Hi,

I've noticed your fork a couple of days while I was casually checking the forks of my github repos: I like it very much! The features you've added in my opinion are interesting and suitable for a general use.

I'd like to start a discussion on the merge of the two: my main concern is how can we reduce external dependencies (of an otherwise little script that I wrote to fill up 2 hours).

Please do open a PR (at your leisure) and let's work on it together.

Thanks for improving the script!

**Comment by kisst** [comment]
Fair shout, we can clearn out the `yq`, and just convert the config to use the same or similar as the QR so the `[nick]:otpauth://totp/{host}?secret={key}&issuer={issuer}`  then the `yq` will be unnecessary, but to generate the qr on cli we need external lib, however I already wrote the script in a way that additional dependencies validate only if a certain sub-module is in use.
For me yq was just an easy way to go as already have it installed almost everywhere but YAML is not always the solution.
So PR is coming and let's continue there.
